# Generated by Django 3.0.8 on 2020-07-30 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('pet_kinds', models.CharField(blank=True, choices=[('고양이', '고양이'), ('강아지', '강아지')], default='강아지', max_length=15, null=True)),
                ('birthday', models.CharField(max_length=10)),
                ('dog_kind', models.CharField(blank=True, choices=[('말티즈', '말티즈'), ('푸들', '푸들'), ('포메라니안', '포메라니안'), ('시츄', '시츄'), ('비숑', '비숑'), ('요크셔테리어', '여크셔테리어'), ('치와와', '치와와'), ('스피츠', '스피츠'), ('믹스견', '믹스견'), ('닥스훈트', '닥스훈트'), ('진도견', '진도견'), ('웰시코기', '웰시코기'), ('시바견', '시바견')], max_length=15, null=True)),
                ('cat_kind', models.CharField(blank=True, choices=[('스코티쉬폴드', '스코티쉬폴드'), ('러시안블루', '러시안블루'), ('먼치킨', '먼치킨'), ('페르시안', '페르시안'), ('샴', '샴'), ('뱅갈', '뱅갈'), ('브리티쉬숏헤어', '브리티쉬숏헤어'), ('터키쉬앙고라', '터키쉬앙고라'), ('아비시니안', '아비시니안'), ('믹스', '믹스')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=15)),
                ('profile', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='pets_photos')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.Pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
