# Generated by Django 3.0.8 on 2020-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_pet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(),
        ),
    ]
