# Generated by Django 3.0.8 on 2020-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200731_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
