# Generated by Django 3.0.8 on 2020-07-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayEvents', to='pets.Pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
