# Generated by Django 3.0.8 on 2020-07-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayevent',
            name='month',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='dayevent',
            name='year',
            field=models.CharField(default=1, max_length=4),
        ),
        migrations.AlterField(
            model_name='dayevent',
            name='date',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
